- pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/ontology.js
Actually not so many changes. The reason that diff shows everything has been changed is I formatted the indent. Test Results in [picsure 388](https://hms-dbmi.atlassian.net/browse/PICSURE-388)
> picsure 388 queryScope - corresponding hpds ui changes

- pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/ontology.js
commit for changes https://hms-dbmi.atlassian.net/browse/ALS-362
https://hms-dbmi.atlassian.net/browse/ALS-427 is also included as it belongs to same code block
> Tom sprint6 - ALS-362

- pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filterList.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/queryBuilder.js
* TODO: test on a non-BDC environment
> ALS-1876: Query template can be passed to filter list

- pic-sure-hpds-ui/src/main/webapp/picsureui/output/outputPanel.js
https://hms-dbmi.atlassian.net/browse/ALS-1918
> Fix: correct updating of query in dataSelection tree on modification 

- pic-sure-hpds-ui/src/main/webapp/picsureui/filter/searchResult.js
https://hms-dbmi.atlassian.net/browse/ALS-1917
> Makes hierarchy selection filter based on paths of results starting with clicked node's path

- pic-sure-hpds-ui/src/main/webapp/picsureui/common/modal.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/common/selection-search-panel-view.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/filter/genomic-filter-view.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
- [Move](https://github.com/hms-dbmi/pic-sure-core-frontend/commit/bce523109dbaac4fdf3d450827e9f897aeb33dd0) @Gcolon021 ['s functionality to common modal](https://github.com/hms-dbmi/pic-sure-core-frontend/commit/bce523109dbaac4fdf3d450827e9f897aeb33dd0)
- [Fix result box overflow bug](https://github.com/hms-dbmi/pic-sure-core-frontend/commit/cab9dbf2b56ccc1f74637bf20f68b2f54c225f68)
- Support for large variable lists or data from the backend.
> [ALS-4464] Selection search box supports infinite scroll with data from the backend or large datasets

- pic-sure-hpds-ui/src/main/webapp/picsureui/output/outputPanel.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/outputPanel.js
- Create title override
- Use ternary to check for override when creating modal
> [ALS-4932] Rename Finalize dataset modal

- pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/queryBuilder.js
This new field supports separate lists of OR filters where the result of each is ANDed with each other.
Depends on: https://github.com/hms-dbmi/pic-sure-hpds/pull/77
> [ALS-4947] Update queryBuilder to use new anyRecordOfMulti field

- pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/queryBuilder.js
- Previously, genes were getting ignored
> [ALS-0000] Support queries with multiple gene clauses

- pic-sure-hpds-ui/src/main/webapp/picsureui/output/outputPanel.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/output/variantExplorer.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/output/variantExplorer.js
- Allow overriding of variant explorer js
> [ALS-4906] Add Variant Explorer in GIC Common Area

- pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/dataset-manage.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/output/package-data-view.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/package-data-view.js
- Also fix the missing modal parameter that was previously passed down from output modal options.
> Add more overrides to allow GIC to hide the save button.

- pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/tokenFunctions.js
[ALS-4794] Update core UI to support no login. Developers can now override the execute function in the core UI router.
> [ALS-4794] Update core UI to support no login

- pic-sure-hpds-ui/src/main/webapp/picsureui/output/variantExplorer.js
> [ALS-5073] Fix Variant Explorer data tables error

- pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.hbs
- pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/header/bannerConfig.js
This banner section can be configured by updating the bannerConfig.json.
> [ALS-5107] Add configurable banner section

- pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.hbs
- pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/header/bannerConfig.js
* [ALS-5107] Add configurable banner section
* [ALS-5107] Gracefully handle file not existing
This banner section can be configured by updating the bannerConfig.json.
> [ALS-5107] Add configurable banner section (#149)

- pic-sure-hpds-ui/src/main/webapp/picsureui/common/tree-select.hbs
- pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filter.hbs
- pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filterList.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/filter/genomic-filter-view.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/output/variantExplorer.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/styles.css
Just a follow up to https://github.com/hms-dbmi/pic-sure-core-frontend/pull/136 after feedback
> [ALS-4918] Style updates and interface changes

- pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/main.js
[ALS-5112] "Open PIC-SURE Explorer" takes the user to a blank page.
> [ALS-5112] "Open PIC-SURE Explorer" takes the user to a blank page

- pic-sure-hpds-ui-extension-archetype/src/main/resources/archetype-resources/src/main/webapp/picsureui/overrides/genomic-filter-view.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/filter/genomic-filter-view.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/genomic-filter-view.js
> [ALS-5334] Make freq description configurable

- pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/dataset-save.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/dataset-view.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/utilities.js
- Add validation for name value to error message in dataset save modal.
- Add anyRecordOf filter rendering dataset view modal.
> [ALS-5244] Bugfix for range vs value logic on dataset string render utility

- pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filter.js
(cherry picked from commit 84cee41502fd484b2269e415d5731c2247853a8a)
> [ALS-5383] Fix bug where UI was stripping spaces from variables. (#177)

- pic-sure-hpds-ui/Dockerfile
- pic-sure-hpds-ui/src/main/webapp/picsureui/common/router.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/dataset-view.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/dataset/utilities.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/filter/filter.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.hbs
- pic-sure-hpds-ui/src/main/webapp/picsureui/header/banner.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/header/header.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/overrides/userDetails.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/queryBuilder.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/picSure/roleFunctions.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/role/addManualStudy.hbs
- pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/role/addManualStudy.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/role/roleManagement.hbs
- pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/role/roleManagement.js
- pic-sure-hpds-ui/src/main/webapp/picsureui/psamaui/user/userDetails.js
> Merging for 03-28 release
